[package]
name = "onCHainRadio"
version = "1.0.0"
authors = []

[addresses]
onChainRadio_add = '583e74f3ff4226454f0263b4e74e07647681e549d93a466c9f45c90bb41dc856'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
