
[package]
name = "onChainRadio"
version = "1.0.0"
authors = []

[addresses]
profile_addr='59d60e525c6ad6a821457e797f85d62220305c081366f824745aac14aaebe4b9'
transaction_addr ='59d60e525c6ad6a821457e797f85d62220305c081366f824745aac14aaebe4b9'


[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]