
[package]
name = "onChainRadio"
version = "1.0.0"
authors = []

[addresses]
profile_addr='0x5d83b2ea7970bd29b1a92e94ae58bd37cb59cb59d5a764a21d01670688871f4d'
transaction_addr ='0x5d83b2ea7970bd29b1a92e94ae58bd37cb59cb59d5a764a21d01670688871f4d'


[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]