
[package]
name = "onChainRadio"
version = "1.0.0"
authors = []

[addresses]
profile_addr='c7bc45497872fcae59a6aa9613ac6614ff2b0d7c4dccf232e37c958600fb5635'



[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]