[package]
name = "onChainRadio"
version = "1.0.0"
authors = []

[addresses]
profile_addr='0xb5422892f64f748f1b2c6f5c7fa0002ba54f35868af03b5a1a62d7ad1b555549'
transaction_addr ='0xb5422892f64f748f1b2c6f5c7fa0002ba54f35868af03b5a1a62d7ad1b555549'


[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
