
[package]
name = "onChainRadio"
version = "1.0.0"
authors = []

[addresses]
profile_addr='43f7d75aff9747a298709ce1bc78aa653a7956a91dee92d27810ac8bf576e7c8'
transaction_addr ='43f7d75aff9747a298709ce1bc78aa653a7956a91dee92d27810ac8bf576e7c8'


[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]