
[package]
name = "onChainRadio"
version = "1.0.0"
authors = []

[addresses]
profile_addr='4bb4d95ba6ff482924084bbfea2af98c634638a77a0c91b909ab9da53a802660'
transaction_addr ='4bb4d95ba6ff482924084bbfea2af98c634638a77a0c91b909ab9da53a802660'


[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]